const dragonLoginTypes = {
  DRAGON_USER: 'DRAGON_USER',
  DRAGON_PASSWORD: 'DRAGON_PASSWORD',
  DRAGON_LOGIN_USER: 'DRAGON_LOGIN_USER',
  DRAGON_LOGIN_PASSWORD: 'DRAGON_LOGIN_PASSWORD',
}

export default dragonLoginTypes